version: '3'

services:
  my_inference_app:
    container_name: my_inference_app_ap
    restart: always
    build: ./my_inference_app
    image: alipoosti/resnet_inference:my_inference_app_ap
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app --timeout 2000
  
  nginx:
    container_name: nginx_ap
    restart: always
    build: ./nginx
    image: alipoosti/resnet_inference:nginx_ap
    ports:
      - "80:80"
    depends_on:
      - my_inference_app